spring.application.name=cinerama
# ==========================================
# CONFIGURACIÓN DE SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/cinerama_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# DEPURACIÓN Y LOGGING (Trazabilidad)
# ==========================================
# Nivel de log para Spring Web (muestra mapeos de rutas y peticiones HTTP)
logging.level.org.springframework.web=DEBUG

# Nivel de log para Hibernate/SQL (muestra consultas e inyección de parámetros)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Logs de la lógica de tu propia aplicación (ajusta con tu paquete base)
logging.level.com.cinerama=DEBUG

# Guardar logs en un archivo físico para auditoría
logging.file.name=logs/cinerama-app.log

# ==========================================
# MANEJO DE ERRORES Y MANIFIESTO HTTP
# ==========================================
# Incluye el mensaje detallado de las excepciones en la respuesta HTTP
spring.web.error.include-message=always

# Incluye la traza de la pila (Stack Trace) en el JSON de error (solo recomendable en desarrollo)
spring.web.error.include-stacktrace=always

# Incluye el cuerpo de la petición que originó el fallo
spring.web.error.include-binding-errors=always
